import type {
  Destination,
  TravelOption,
  CurrencyCode,
} from "./types";

// ─── Destinations ─────────────────────────────────────────────────────────────

export const destinations: Destination[] = [
  {
    id: "dest-orlando",
    name: "Orlando",
    country: "United States",
    countryCode: "US",
    region: "Florida",
    iataCode: "MCO",
    geo: { lat: 28.5383, lng: -81.3792 },
    timezone: "America/New_York",
    currency: "USD",
    coverImage: {
      url: "https://images.unsplash.com/photo-1575089976121-8ed7b2a54265?w=1200&q=80",
      alt: "Orlando skyline at sunset",
    },
    description: "Theme park capital of the world with year-round sunshine.",
    popularFor: ["Theme Parks", "Family Fun", "Shopping", "Golf"],
    bestTimeToVisit: "Jan–Apr",
  },
  {
    id: "dest-las-vegas",
    name: "Las Vegas",
    country: "United States",
    countryCode: "US",
    region: "Nevada",
    iataCode: "LAS",
    geo: { lat: 36.1699, lng: -115.1398 },
    timezone: "America/Los_Angeles",
    currency: "USD",
    coverImage: {
      url: "https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d?w=1200&q=80",
      alt: "Las Vegas Strip at night",
    },
    description: "Entertainment, nightlife, and world-class dining in the Nevada desert.",
    popularFor: ["Casinos", "Shows", "Nightlife", "Fine Dining"],
    bestTimeToVisit: "Mar–May, Sep–Nov",
  },
  {
    id: "dest-nyc",
    name: "New York City",
    country: "United States",
    countryCode: "US",
    region: "New York",
    iataCode: "JFK",
    geo: { lat: 40.7128, lng: -74.006 },
    timezone: "America/New_York",
    currency: "USD",
    coverImage: {
      url: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&q=80",
      alt: "New York City skyline",
    },
    description: "The city that never sleeps — culture, food, and iconic landmarks.",
    popularFor: ["Museums", "Broadway", "Food", "Shopping"],
    bestTimeToVisit: "Apr–Jun, Sep–Nov",
  },
  {
    id: "dest-miami",
    name: "Miami",
    country: "United States",
    countryCode: "US",
    region: "Florida",
    iataCode: "MIA",
    geo: { lat: 25.7617, lng: -80.1918 },
    timezone: "America/New_York",
    currency: "USD",
    coverImage: {
      url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
      alt: "Miami Beach aerial",
    },
    description: "Sun, sand, art deco, and a vibrant Latin cultural scene.",
    popularFor: ["Beaches", "Nightlife", "Art", "Cuban Food"],
    bestTimeToVisit: "Nov–Apr",
  },
  {
    id: "dest-cancun",
    name: "Cancún",
    country: "Mexico",
    countryCode: "MX",
    iataCode: "CUN",
    geo: { lat: 21.1619, lng: -86.8515 },
    timezone: "America/Cancun",
    currency: "MXN",
    coverImage: {
      url: "https://images.unsplash.com/photo-1510097467424-192d713fd8b2?w=1200&q=80",
      alt: "Cancún turquoise water beach",
    },
    description: "Crystal-clear Caribbean waters, Mayan ruins, and all-inclusive resorts.",
    popularFor: ["Beaches", "Snorkeling", "Mayan Ruins", "Resorts"],
    bestTimeToVisit: "Dec–Apr",
  },
  {
    id: "dest-paris",
    name: "Paris",
    country: "France",
    countryCode: "FR",
    iataCode: "CDG",
    geo: { lat: 48.8566, lng: 2.3522 },
    timezone: "Europe/Paris",
    currency: "EUR",
    coverImage: {
      url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&q=80",
      alt: "Eiffel Tower in Paris",
    },
    description: "The City of Light — art, fashion, cuisine, and timeless romance.",
    popularFor: ["Museums", "Fashion", "Cuisine", "Architecture"],
    bestTimeToVisit: "Apr–Jun, Sep–Oct",
  },
];

// ─── Helper constructors ──────────────────────────────────────────────────────

function usd(amount: number, unit: "total" | "per_night" | "per_day" | "per_person" = "total") {
  return { amount, currency: "USD" as CurrencyCode, unit, taxesIncluded: false };
}

function rating(score: number, reviewCount: number, source = "Google") {
  return [{ score, reviewCount, source }];
}

function mockMeta(id: string) {
  return {
    source: "mock" as const,
    externalId: id,
    deepLink: "https://www.google.com/travel",
    lastUpdated: new Date().toISOString(),
  };
}

// ─── Mock Travel Options ──────────────────────────────────────────────────────

export const travelOptions: TravelOption[] = [

  // ── FLIGHTS ────────────────────────────────────────────────────────────────

  {
    id: "flight-1",
    category: "flights",
    details: {
      outbound: [{
        origin: "ORD", destination: "MCO",
        departureAt: "2025-10-15T06:00:00", arrivalAt: "2025-10-15T09:35:00",
        airline: "Spirit Airlines", flightNumber: "NK1042",
        durationMinutes: 155, cabin: "economy", stops: 0,
      }],
      inbound: [{
        origin: "MCO", destination: "ORD",
        departureAt: "2025-10-19T20:00:00", arrivalAt: "2025-10-19T21:40:00",
        airline: "Spirit Airlines", flightNumber: "NK1043",
        durationMinutes: 160, cabin: "economy", stops: 0,
      }],
      baggage: { carry_on: true, checked: 0 },
      fareName: "Basic Economy",
      isRefundable: false,
      seatsRemaining: 4,
    },
    title: "Basic Economy — Nonstop",
    provider: "Spirit Airlines",
    price: usd(149),
    ratings: rating(3.8, 12400),
    description: "Cheapest available nonstop round-trip. Personal item only — upgrade bags for a fee.",
    highlights: ["Nonstop both ways", "Personal item included", "Early morning departure", "4 seats left at this price"],
    media: [],
    tags: ["nonstop", "cheapest", "basic"],
    isFeatured: false,
    isBestValue: false,
    providerMeta: mockMeta("flight-1"),
  },
  {
    id: "flight-2",
    category: "flights",
    details: {
      outbound: [{
        origin: "ORD", destination: "MCO",
        departureAt: "2025-10-15T09:30:00", arrivalAt: "2025-10-15T13:10:00",
        airline: "Southwest Airlines", flightNumber: "WN2210",
        durationMinutes: 160, cabin: "economy", stops: 0,
      }],
      inbound: [{
        origin: "MCO", destination: "ORD",
        departureAt: "2025-10-19T15:30:00", arrivalAt: "2025-10-19T17:15:00",
        airline: "Southwest Airlines", flightNumber: "WN2211",
        durationMinutes: 165, cabin: "economy", stops: 0,
      }],
      baggage: { carry_on: true, checked: 2 },
      fareName: "Wanna Get Away",
      isRefundable: false,
      seatsRemaining: 9,
    },
    title: "Wanna Get Away — 2 Bags Free",
    provider: "Southwest Airlines",
    price: usd(218),
    ratings: rating(4.4, 89200),
    description: "Southwest's value fare with 2 free checked bags — real savings vs. Spirit when you pack.",
    highlights: ["2 free checked bags", "No change fees", "Nonstop available", "Mid-morning departure"],
    media: [],
    tags: ["nonstop", "bags-included", "flexible"],
    isFeatured: false,
    isBestValue: true,
    providerMeta: mockMeta("flight-2"),
  },
  {
    id: "flight-3",
    category: "flights",
    details: {
      outbound: [{
        origin: "ORD", destination: "MCO",
        departureAt: "2025-10-15T11:00:00", arrivalAt: "2025-10-15T16:30:00",
        airline: "American Airlines", flightNumber: "AA304",
        durationMinutes: 270, cabin: "economy", stops: 1,
      }],
      inbound: [{
        origin: "MCO", destination: "ORD",
        departureAt: "2025-10-19T18:00:00", arrivalAt: "2025-10-19T22:10:00",
        airline: "American Airlines", flightNumber: "AA305",
        durationMinutes: 250, cabin: "economy", stops: 1,
      }],
      baggage: { carry_on: true, checked: 0 },
      fareName: "Main Cabin",
      isRefundable: true,
      seatsRemaining: 22,
    },
    title: "Main Cabin — Fully Refundable",
    provider: "American Airlines",
    price: usd(289),
    ratings: rating(4.2, 203000),
    description: "Fully refundable main cabin with seat selection. 1-stop each way through Charlotte.",
    highlights: ["Fully refundable", "Seat selection included", "Miles accrual", "Same-day change available"],
    media: [],
    tags: ["refundable", "flexible", "1-stop"],
    isFeatured: true,
    isBestValue: false,
    providerMeta: mockMeta("flight-3"),
  },

  // ── HOTELS ─────────────────────────────────────────────────────────────────

  {
    id: "hotel-1",
    category: "hotels",
    details: {
      starRating: 2,
      roomType: "Standard Queen",
      bedType: "Queen",
      amenities: ["Free WiFi", "Pool", "Free Parking"],
      checkInTime: "15:00",
      checkOutTime: "11:00",
      cancellationPolicy: "free",
      breakfastIncluded: false,
      distanceFromCenterKm: 4.2,
    },
    title: "Motel 6 Orlando — International Drive",
    provider: "Motel 6",
    price: usd(62, "per_night"),
    ratings: rating(3.9, 4800, "TripAdvisor"),
    description: "Clean, no-frills budget motel 10 minutes from Disney Springs. Free parking saves you $30/night vs. resort fees.",
    highlights: ["Free parking (saves $30+/night)", "Outdoor pool", "Free cancellation", "10 min to Disney Springs"],
    media: [{
      url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
      alt: "Budget motel room",
    }],
    address: { city: "Orlando", region: "FL", country: "US" },
    tags: ["budget", "free-parking", "pool"],
    isFeatured: false,
    isBestValue: false,
    providerMeta: mockMeta("hotel-1"),
  },
  {
    id: "hotel-2",
    category: "hotels",
    details: {
      starRating: 3,
      roomType: "Deluxe King",
      bedType: "King",
      amenities: ["Free WiFi", "Pool", "Fitness Center", "Free Breakfast", "Shuttle to Parks"],
      checkInTime: "16:00",
      checkOutTime: "12:00",
      cancellationPolicy: "free",
      breakfastIncluded: true,
      distanceFromCenterKm: 2.1,
    },
    title: "Rosen Inn International — Park Shuttle",
    provider: "Rosen Hotels",
    price: usd(99, "per_night"),
    ratings: rating(7.8, 12100, "Booking.com"),
    description: "Well-located 3-star with complimentary hot breakfast and free Disney/Universal shuttle — exceptional value on I-Drive.",
    highlights: ["Free hot breakfast", "Free park shuttle", "2 pools + hot tub", "Free cancellation"],
    media: [{
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
      alt: "Hotel pool area",
    }],
    address: { city: "Orlando", region: "FL", country: "US" },
    tags: ["breakfast-included", "shuttle", "pool", "best-value"],
    isFeatured: false,
    isBestValue: true,
    providerMeta: mockMeta("hotel-2"),
  },
  {
    id: "hotel-3",
    category: "hotels",
    details: {
      starRating: 4,
      roomType: "Premium Suite",
      bedType: "King",
      amenities: ["Free WiFi", "Spa", "Multiple Pools", "Room Service", "Concierge", "Valet Parking"],
      checkInTime: "15:00",
      checkOutTime: "11:00",
      cancellationPolicy: "partial",
      breakfastIncluded: false,
      distanceFromCenterKm: 0.5,
    },
    title: "Hyatt Regency Orlando",
    provider: "Hyatt",
    price: usd(189, "per_night"),
    ratings: rating(8.6, 31400, "Expedia"),
    description: "Upscale convention-connected property with a lazy river and rooftop bar — splurge option with World Points.",
    highlights: ["Lazy river & resort pool", "Rooftop bar with city views", "Direct convention center access", "World of Hyatt points"],
    media: [{
      url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
      alt: "Luxury hotel pool",
    }],
    address: { city: "Orlando", region: "FL", country: "US" },
    tags: ["luxury", "points", "spa", "rooftop"],
    isFeatured: true,
    isBestValue: false,
    providerMeta: mockMeta("hotel-3"),
  },

  // ── CAR RENTALS ────────────────────────────────────────────────────────────

  {
    id: "car-1",
    category: "carRentals",
    details: {
      vehicleClass: "economy",
      transmissionType: "automatic",
      seats: 5,
      unlimitedMileage: true,
      features: ["A/C", "Bluetooth", "USB Charging"],
      pickupLocation: { city: "Orlando", region: "FL", country: "US", street: "MCO Airport Terminal A" },
      insuranceIncluded: false,
    },
    title: "Economy Car — Unlimited Miles",
    provider: "Rentalcars.com",
    price: usd(29, "per_day"),
    ratings: rating(4.1, 6700),
    description: "Toyota Yaris or similar. Unlimited mileage with fuel policy clear-to-clear. Book early — economy sells out fast at MCO.",
    highlights: ["Unlimited mileage", "Airport pickup included", "No mileage fees", "Free cancellation"],
    media: [],
    tags: ["economy", "unlimited-miles", "airport"],
    isFeatured: false,
    isBestValue: false,
    providerMeta: { ...mockMeta("car-1"), deepLink: "https://www.rentalcars.com" },
  },
  {
    id: "car-2",
    category: "carRentals",
    details: {
      vehicleClass: "suv",
      transmissionType: "automatic",
      seats: 7,
      unlimitedMileage: true,
      features: ["A/C", "GPS", "Bluetooth", "USB Charging", "Third Row", "Backup Camera"],
      pickupLocation: { city: "Orlando", region: "FL", country: "US", street: "MCO Airport Terminal B" },
      insuranceIncluded: true,
    },
    title: "7-Seat SUV — Insurance Included",
    provider: "Enterprise",
    price: usd(64, "per_day"),
    ratings: rating(4.5, 28900),
    description: "Chevy Tahoe or similar with full coverage insurance bundled in. Best for families — fits luggage for 5+.",
    highlights: ["Insurance included — no surprises", "7 seats + cargo space", "Unlimited mileage", "24/7 roadside assistance"],
    media: [],
    tags: ["suv", "family", "insurance-included", "7-seat"],
    isFeatured: false,
    isBestValue: true,
    providerMeta: { ...mockMeta("car-2"), deepLink: "https://www.enterprise.com" },
  },

  // ── FOOD ───────────────────────────────────────────────────────────────────

  {
    id: "food-1",
    category: "food",
    details: {
      cuisine: ["American", "BBQ"],
      priceLevel: 1,
      mustTryDishes: ["Pulled Pork Sandwich", "Loaded Fries", "Sweet Tea"],
      openNow: true,
      reservationRequired: false,
      address: { street: "8225 International Dr", city: "Orlando", region: "FL", country: "US" },
      hours: "Mon–Sun 11am–10pm",
    },
    title: "Bubbalou's Bodacious Bar-B-Que",
    provider: "Local Pick",
    price: usd(12, "per_person"),
    ratings: rating(8.2, 3400, "Yelp"),
    description: "Orlando institution since 1979. Heaping BBQ plates for under $15 — lines out the door on weekends for a reason.",
    highlights: ["Orlando's #1 BBQ since 1979", "Under $15 a plate", "Walk-in only", "Cash & card accepted"],
    media: [{
      url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
      alt: "BBQ platter with sides",
    }],
    address: { street: "8225 International Dr", city: "Orlando", region: "FL", country: "US" },
    tags: ["bbq", "local", "cheap-eats", "no-reservation"],
    isFeatured: false,
    isBestValue: true,
    providerMeta: { ...mockMeta("food-1"), deepLink: "https://www.yelp.com" },
  },
  {
    id: "food-2",
    category: "food",
    details: {
      cuisine: ["Mexican", "Tex-Mex"],
      priceLevel: 1,
      mustTryDishes: ["Carne Asada Tacos", "Horchata", "Guacamole"],
      reservationRequired: false,
      address: { street: "4946 S Orange Ave", city: "Orlando", region: "FL", country: "US" },
      hours: "Tue–Sun 10am–9pm",
    },
    title: "Hunger Street Tacos",
    provider: "Local Pick",
    price: usd(8, "per_person"),
    ratings: rating(9.1, 1800, "Google"),
    description: "Tiny taqueria beloved by locals — $3 tacos and $2 horchata. The al pastor is a must. Cash preferred.",
    highlights: ["$3 tacos", "Cash preferred", "Local neighborhood gem", "Al pastor made fresh daily"],
    media: [{
      url: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
      alt: "Street tacos on corn tortillas",
    }],
    address: { street: "4946 S Orange Ave", city: "Orlando", region: "FL", country: "US" },
    tags: ["tacos", "ultra-cheap", "local-favorite", "cash"],
    isFeatured: true,
    isBestValue: true,
    providerMeta: { ...mockMeta("food-2"), deepLink: "https://www.google.com/maps" },
  },

  // ── ACTIVITIES ─────────────────────────────────────────────────────────────

  {
    id: "activity-1",
    category: "activities",
    details: {
      type: "tour",
      durationMinutes: 90,
      groupSize: "large_group",
      physicalLevel: "easy",
      includes: ["Guide", "Bottled Water", "Map"],
      meetingPoint: "Orange County Convention Center Main Lobby",
      languages: ["English", "Spanish"],
      instantConfirmation: true,
    },
    title: "I-Drive Walking Food & Culture Tour",
    provider: "Viator",
    price: usd(29, "per_person"),
    ratings: rating(8.9, 540, "Viator"),
    description: "90-minute guided walk through International Drive's best food stalls and hidden gems. Includes 4 tastings.",
    highlights: ["4 food tastings included", "Local guide", "Instant confirmation", "Cancellation up to 24hr before"],
    media: [{
      url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
      alt: "Food tour group at market",
    }],
    address: { city: "Orlando", region: "FL", country: "US" },
    tags: ["food-tour", "walking", "tastings"],
    isFeatured: false,
    isBestValue: false,
    providerMeta: { ...mockMeta("activity-1"), deepLink: "https://www.viator.com" },
  },
  {
    id: "activity-2",
    category: "activities",
    details: {
      type: "nature",
      durationMinutes: 120,
      groupSize: "small_group",
      physicalLevel: "easy",
      includes: ["Airboat Ride", "Wildlife Viewing", "Guide"],
      meetingPoint: "Boggy Creek Airboat Adventures, 3702 Big Bass Rd, Kissimmee, FL",
      languages: ["English"],
      instantConfirmation: true,
    },
    title: "Boggy Creek Airboat Ride + Gator Spotting",
    provider: "GetYourGuide",
    price: usd(35, "per_person"),
    ratings: rating(9.2, 2200, "GetYourGuide"),
    description: "Glide through real Florida Everglades wetlands 20 minutes from Disney. Spot wild alligators, eagles, and manatees.",
    highlights: ["Wild alligator sightings guaranteed", "20 min from Disney", "Small group max 18 people", "Great for all ages"],
    media: [{
      url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
      alt: "Airboat on Florida swamp",
    }],
    address: { city: "Kissimmee", region: "FL", country: "US" },
    tags: ["outdoors", "wildlife", "airboat", "family"],
    isFeatured: true,
    isBestValue: true,
    providerMeta: { ...mockMeta("activity-2"), deepLink: "https://www.getyourguide.com" },
  },
  {
    id: "activity-3",
    category: "activities",
    details: {
      type: "cultural",
      durationMinutes: 240,
      groupSize: "large_group",
      physicalLevel: "easy",
      includes: ["Admission", "Self-guided Audio Tour"],
      languages: ["English", "Spanish", "French", "German"],
      instantConfirmation: false,
    },
    title: "Kennedy Space Center — Explorer Ticket",
    provider: "KSC Visitor Complex",
    price: usd(57, "per_person"),
    ratings: rating(9.0, 44000, "TripAdvisor"),
    description: "Experience Space Shuttle Atlantis, IMAX films, and real rocket launches 45 min from Orlando. One of America's best museums.",
    highlights: ["Space Shuttle Atlantis on display", "Real rocket launch viewing available", "IMAX included", "4hr+ of content"],
    media: [{
      url: "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=800&q=80",
      alt: "Space shuttle on display",
    }],
    address: { city: "Merritt Island", region: "FL", country: "US" },
    tags: ["museum", "space", "educational", "iconic"],
    isFeatured: false,
    isBestValue: false,
    providerMeta: { ...mockMeta("activity-3"), deepLink: "https://www.kennedyspacecenter.com" },
  },

  // ── EXTRAS ─────────────────────────────────────────────────────────────────

  {
    id: "extra-1",
    category: "extras",
    details: {
      type: "insurance",
      coverageDetails: "Trip cancellation up to $5,000. Medical evacuation up to $500,000. Lost baggage up to $1,500.",
    },
    title: "Essential Travel Protection",
    provider: "SafeTrip (AIG)",
    price: usd(22),
    ratings: rating(4.3, 8900),
    description: "Basic trip protection covering cancellation, medical, and baggage. Recommended for any international or flight-inclusive trip.",
    highlights: ["$5K trip cancellation", "$500K medical evacuation", "$1.5K baggage protection", "24/7 assistance hotline"],
    media: [],
    tags: ["insurance", "protection", "recommended"],
    isFeatured: false,
    isBestValue: false,
    providerMeta: mockMeta("extra-1"),
  },
  {
    id: "extra-2",
    category: "extras",
    details: {
      type: "sim_card",
      coverageDetails: "10GB data, unlimited calls & texts within USA, 30-day validity.",
    },
    title: "USA Prepaid SIM Card — 10GB",
    provider: "T-Mobile",
    price: usd(30),
    ratings: rating(4.6, 3200),
    description: "Avoid roaming charges — T-Mobile prepaid SIM with 10GB LTE. Perfect for international visitors with unlocked phones.",
    highlights: ["10GB high-speed LTE", "Unlimited calls & texts", "No contract required", "Works in all 50 states"],
    media: [],
    tags: ["sim", "data", "international"],
    isFeatured: false,
    isBestValue: false,
    providerMeta: mockMeta("extra-2"),
  },
];

// ─── Helper: get options by destination (extend when real API exists) ──────────

export function getOptionsForDestination(
  _destinationId: string
): TravelOption[] {
  // In production, this is replaced by real API calls keyed to destination.
  // Mock returns the same pool for every destination.
  return travelOptions;
}
